### ISSUE TITLE
Loot only guns from the bots. CS:GO.

### ISSUE THREAD

**Issue by firuzjumaev** [Rudokhvist/Selective-Loot-and-Transfer-Plugin#5]
Hi,
Is it possible to loot only guns from the bot's inventory, Now bot has case, graffiti and gun, I just want to send only guns to the Master.
Thanks,

**Comment by Rudokhvist** [comment]
This plugin won't help you in this. And none of my free plugins will. I don't know if there is a plugin for your needs, I was just saying that it's technically possible. I sell semi-related plugin, but I'm not even sure that it will be enough for you. If you are willing to pay - contact me for details.
